# fly.toml app configuration file generated for fso-pokedex-cz on 2024-04-18T00:26:25-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fso-pokedex-cz'
primary_region = 'iad'

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
